      SUBROUTINE CONFAC (AL,OBJDIS,OBJL,FATOSK,FATOBJ)
 
      Implicit None
        
      REAL AL,FATOBJ,FATOSK,OBJDIS,OBJL,RR1,RR2,X 

C     #18 DISC - DISC; CONFIGURATION FACTOR,APPENDIX C,SIEGEL & HOWELL

      RR1=(AL/2.)/OBJDIS  
      RR2=(OBJL/2.)/OBJDIS
      X=1.+(1.+RR2**2)/RR1**2 
      FATOBJ=0.5*(X-(X**2-4.*(RR2/RR1)**2)**.5)   
C     FATOSK=0.4 USUALLY; ASSUME THAT OBJECT ONLY SUBTENDS PART OF SKY
c      FATOSK=0.4-FATOBJ   

      RETURN  
      END
